version = 0.1
[default.deploy.parameters]
stack_name = "slack-assistant-bot"
resolve_s3 = true
s3_prefix = "slack-assistant-bot"
region = "ap-northeast-3"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
