AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  AssistantChatBot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bot
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 180
      Events:
        Handle:
          Type: Api
          Properties:
            Path: /slack/events
            Method: POST
      Environment:
        Variables:
          SERVER_RUNNING_MODE: Prod
          SLACK_SIGN_SECRET: Dummy
          SLACK_BOT_TOKEN: Dummy
          OPENAI_TOKEN: Dummy

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - index.ts
